
# Set up libraries and directory
```{r}
getwd()
setwd("~/")
library(sjPlot)
library(ggeffects)
library(scales)
library(ggplot2)
library(vegan)
```


# Read and crop metadata
```{r}
all.metadata <- read.csv("metadata.csv")
all.metadata2 <- all.metadata[1:38,]

# Order is a count of the number of reads per order per sample
order.taxa <- read.csv("corder_taxa.csv")
order.taxa[is.na(order.taxa)] <- 0  
order.taxa <- order.taxa[1:38,]

# Use a species accumulation curve to find the estimated total diversity
order.specaccum <- specaccum(order.taxa)

# I presume we had some logic for trimming it in this way
order.taxa.cut <- order.taxa[11:38,]
rich.adcp <- specaccum(order.taxa.cut)
rich.adcp <- rich.adcp$richness
rich.adcp <- rich.adcp[11:38]
```

```{r}
# This code lets us analyze the relationship between echo amplitude and richness

adcp.df <- data.frame("Echo Amplitude" = all.metadata2$Echo.Amplitude, "Richness" = order.specaccum$richness)
adcp.richness <- lm(Richness ~ Echo.Amplitude, adcp.df)
plot(all.metadata2$Echo.Amplitude, order.specaccum$richness)
summary(adcp.richness)
adcp.richness
g <- plot_model(adcp.richness, type = "pred", term = "Echo.Amplitude") + 
  ggtitle("Echo Amplitude and Species Richness") + 
  labs(x = "Order richness of eDNA samples", y = "Echo amplitude")
plot(g)

class.taxa <- read.csv("class_taxa.csv")
class.taxa[is.na(class.taxa)] <- 0  # Replace NaN & Inf with NA
class.taxa <- class.taxa[1:38,]

# note - for me this regression's significance shows that cutting out unlikely species 
# did not significantly alter the biodiversity of the sample
order.cut.v.uncut <- lm(SWDivOrderUncut ~ SWDivOrderCut, all.metadata2)
summary(order.cut.v.uncut)
plot(all.metadata2$SWDivOrderUncut, all.metadata2$SWDivClassUncut)

```

```{r}
# this shows that order diversity correlates with class diversity, indicating diversity holds pretty strongly
# at multiple phylogenetic levels when we didn't cut anything
order.v.class <- lm(SWDivOrderUncut ~ SWDivClassUncut, all.metadata2)
summary(order.v.class)
f <- plot_model(order.v.class, type = "pred", term = "SWDivOrderUncut") + ggtitle(title = "Shannon-Weiner Diversity Index of Classes versus Shannon-Weiner Diversity of Orders", y = "Shannon-Weiner diversity of classes")
plot(f)

# however, trimming with classes appears to have altered the diversity measured pretty significantly
class.cut.v.uncut <- lm(SWDivClassUncut ~ SWDivClassCut, all.metadata2)
summary(class.cut.v.uncut) 

# this further demonstrates our classes trimming altered the diversity of samples pretty strongly. rip
order.v.class.cut <- lm(SWDivOrderCut ~ SWDivClassCut, all.metadata2)
summary(order.v.class.cut)

#Almost significant relationship - includes all orders detected
order.div.chla <- lm(Chla.Fluoro..V. ~ SWDivOrderUncut, all.metadata2)
summary(order.div.chla)
plot(all.metadata2$Chla.Fluoro..V., all.metadata2$SWDivClassUncut)

order.div.chla2 <- lm(SWDivOrderUncut ~ Chla.Fluoro..V., all.metadata2)
summary(order.div.chla2) 
plot(all.metadata2$Chla.Fluoro..V., all.metadata2$SWDivClassUncut)


# Significant relationship - potentially demonstrates that as biovolume increases,
# species composition becomes more uniform
order.zoop.uncut <- lm(MeterNetZooplanktonVol ~ SWDivOrderUncut, all.metadata2)
summary(order.zoop.uncut)
e <- plot_model(order.zoop.uncut, type = "pred", term = "SWDivOrderUncut") + 
  ggtitle("Sample Biodiversity and Meter Net Zooplankton Volume") + 
  labs(x = "Order diversity of eDNA samples (Shannon-Weiner diversity index)", y = "Meter net zooplankton volume (mL)")
plot(e)
```

```{r}
# these are multivariate analyses of diversity and inorganic variables - not finding anything significant 
# Replace NaN & Inf with NA
order.taxa <- order.taxa[11:38,]

chla.order <- adonis(order.taxa ~ all.metadata2$Chla.Fluoro..V., method = "bray")
chla.order

sal.order <- adonis(order.taxa ~ all.metadata2$Salinity..psu., method = "bray")
sal.order

o2.order <- adonis(order.taxa ~ all.metadata2$O2.Seapoint..mL.L., method = "bray")
o2.order

depth.order <- adonis(order.taxa ~ all.metadata2$Z.Corr..m., method = "bray")
depth.order


length(class.taxa)
length(order.taxa)

chla.class <- adonis(class.taxa ~ all.metadata$Chla.Fluoro..V., method = "bray")
chla.class

sal.class <- adonis(class.taxa ~ all.metadata$Salinity..psu., method = "bray")
sal.class

o2.class <- adonis(class.taxa ~ all.metadata$O2.Seapoint..mL.L., method = "bray")
o2.class


# Multivariate analysis combining environmental variables. Became more significant
# when I added salinity in. Sea composition predicts richness. 

df.vals <- data.frame(all.metadata2$O2.Seapoint..mL.L., all.metadata2$Sal..psu.)
df.time <- data.frame(all.metadata2$Start.Time, all.metadata2$DEPTH)

# Significant
env.order <- adonis(df.vals ~ order.specaccum$richness, method = "bray")
env.order

ggplot(env.order$aov.tab) + 
  stat_ellipse(aes(x=NMDS1,y=NMDS2,colour=trt),level = 0.50) +
  geom_point(aes(x=NMDS1,y=NMDS2,shape=trt,colour=trt),size=4) + 
  theme_mine()

time.order <- adonis(df.time ~ order.specaccum$richness, method = "bray")
time.order

# Not significant with SWDiversity
env.order <- adonis(df.vals ~ all.metadata2$SWDivOrderUncut, method = "bray")
env.order

time.order <- adonis(df.time ~ all.metadata2$SWDivOrderUncut, method = "bray")
time.order
```

```{r}
# we should talk with shaili tmw about this, just trying something
class.specaccum <- specaccum(class.taxa)
df.specrich.chla <- data.frame(class.specaccum$richness, all.metadata2$Chla.Fluoro..V.)
specaccum.lm <- lm(class.specaccum.richness ~ all.metadata2.Chla.Fluoro..V., df.specrich.chla)
summary(specaccum.lm)
order.specaccum <- specaccum(order.taxa)

df.specrich.chla.order <- data.frame(order.specaccum$richness, all.metadata2$Chla.Fluoro..V.)
specaccum.lm.order.chla <- lm(order.specaccum.richness ~ all.metadata2.Chla.Fluoro..V., df.specrich.chla.order)
summary(specaccum.lm.order.chla)
g <- plot_model(specaccum.lm.order.chla, type = "pred", term = "all.metadata2.Chla.Fluoro..V.") + ggtitle("Chlorophyll-a concentration and Order Richness") + labs(x = "Chlorophyll-a concentration", y = "Order diversity (Shannon-Weiner diversity index)") + ggplot(adcp.df, aes(x = Echo.Amplitude, y = Richness)) + geom_point()
plot(g)


df.specrich.o2.order <- data.frame(order.specaccum$richness, all.metadata2$O2.Seapoint..mL.L.)
specaccum.lm.order.o2 <- lm(order.specaccum.richness ~ all.metadata2.O2.Seapoint..mL.L., df.specrich.o2.order)
summary(specaccum.lm.order.o2)
g <- plot_model(specaccum.lm.order.o2, type = "pred", term = "all.metadata2.O2.Seapoint..mL.L.") + ggtitle("Oxygen Concentration and Order Richness") + labs(x = "Oxygen concentration (mL/L)", y = "Order richness")
plot(g)


df.specrich.sal.order <- data.frame(order.specaccum$richness, all.metadata2$Sal..psu.)
specaccum.lm.order.sal <- lm(order.specaccum.richness ~ all.metadata2.Sal..psu., df.specrich.sal.order)
summary(specaccum.lm.order.sal)
g <- plot_model(specaccum.lm.order.sal, type = "pred", term = "all.metadata2.Sal..psu.") + ggtitle("Salinity and Order Richness") + labs(x = "Salinity (psu)", y = "Order richness")
plot(g)

total.lat <- (all.metadata2$LatDeg + (all.metadata2$LatMin/60))
total.lat
df.lat.richness <- data.frame(total.lat, order.specaccum$richness)
plot(total.lat, order.specaccum$richness) + title("Order Richness and Latitude")

# Significant relationship between latitude and richness
lat.richness <- lm(total.lat ~ order.specaccum$richness)

df.lat.richness <- data.frame("Latitude" = total.lat, "Richness" = order.specaccum$richness)
plot(df.lat.richness$Latitude, df.lat.richness$Richness, ylab = "Order Richness", xlab = "Latitude") + title("Order Richness and Latitude") 
ggplot(df.lat.richness, aes(Latitude, Latitude)) + points(x = "Latitude")

summary(lat.richness)

# Almost significant relationship between latitude and diversity, except for few outliers
# Decrease in diversity at 10 degrees may be sign of shoaling OMZ - DSL team noticed similar trends
lat.div <- lm(total.lat ~ all.metadata2$SWDivOrderUncut)
plot(total.lat, all.metadata2$SWDivOrderUncut)
summary(lat.div)

# No significant relationship between ADCP echo amplitude and SW Diversity
adcp.div <- lm(all.metadata2$Echo.Amplitude ~ all.metadata2$SWDivOrderUncut)
plot(all.metadata2$SWDivOrderUncut, all.metadata2$Echo.Amplitude)
summary(adcp.div)

# Significant negative relationship. Lol.


# Significant relationship bewteen zooplankton diversity and eDNA diversity
order.v.class <- lm(SWDivClassUncut ~ SWDivOrderUncut, all.metadata2)
summary(order.v.class)
e <- plot_model(order.v.class, type = "pred", term = "SWDivOrderUncut") +
  labs(x = "Order diversity of eDNA samples (Shannon-Weiner diversity index)", 
       y = "Class diversity of eDNA samples (Shannon-Weiner diversity index)")
plot(e)

# Significant relationship bewteen zooplankton diversity and eDNA diversity
meter.div.sw.div <- lm(Meter.Net.Diversity ~ SWDivOrderUncut, all.metadata2)
plot(all.metadata2$SWDivOrderUncut, all.metadata2$Meter.Net.Diversity)
summary(meter.div.sw.div)
e <- plot_model(meter.div.sw.div, type = "pred", term = "SWDivOrderUncut") + 
  ggtitle("Sample Biodiversity and Meter Net Zooplankton Diversity") + 
  labs(x = "Order diversity of eDNA samples (Shannon-Weiner diversity index)", 
       y = "Meter net ooplankton diversity (Shannon-Weiner diversity index)")
plot(e)

meter.div.richness <- lm(all.metadata2$Meter.Net.Diversity ~ order.specaccum$richness)
plot(all.metadata2$Meter.Net.Diversity, order.specaccum$richness)
summary(meter.div.richness)

anova(meter.div.sw.div)

rc.dissimilarity <- raupcrick(order.taxa)
rc.dissimilarity

bray.diss <- vegdist(order.taxa, "bray")
bray.diss


hclust
pca
```
