---
title: "illumina_analyses"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(vegan)
library(dplyr)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(gridExtra)
```


```{r load data}

setwd("~/teamedna")

illumina <- read.delim("illumina_data.txt", row.names = NULL, stringsAsFactors = FALSE)

all.metadata <- read_csv("final_hydrowork.csv")
all.metadata <- all.metadata[!is.na(all.metadata$SAMPLE),]
all.metadata$SAMPLE
sample.id

all.metadata$`Updated Location`

colnames(illumina.nocon)

illumina.nocon <- subset(illumina, select = -c(X12S_Sample.EB.combined, X12S_Sample.FB.combined,X12S_Sample3.4.StatNo.3, X12S_Sample27.11.StatNo.41))

illumina$X12S_San

all.controls <- illumina$X12S_Sample.EB.combined + illumina$X12S_Sample.FB.combined

all.controls.bin <- all.controls
all.controls.bin[all.controls.bin > 0] <- 1

controls.df <- data.frame("taxon" = illumina$sum.taxonomy, "controls" = all.controls.bin)
controls.inds <- which(controls.df$controls > 0)
con.rownames <- controls.df[controls.inds, "taxon"]
con.rownames <- na.omit(c(con.rownames))

illumina.nocon <- illumina.nocon[-con.rownames,]
illumina.nocon <- illumina.nocon[1:474,]


taxonomy <- illumina.nocon$sum.taxonomy


rownames(illumina.nocon) <- illumina.nocon$sum.taxonomy
illumina.nocon <- illumina.nocon[,2:length(colnames(illumina.nocon))]
illumina.nocon

colSums(illumina.nocon)
rowSums(data.frame(t(illumina.nocon)))
colnames(illumina.nocon)

illumina.nocon

sample.id2 <- c("12.2", "12.3", "16.2", "16.3", "17.1", "17.2", "17.3", "17.4", "18.2", "18.3", "19.1", "19.2", "28.1", "28.11", "28.2", "45.11", "45.12", "41.11", "3.1", "3.2", "3.3", "3.4", "4.1", "4.2", "4.1", "5.2", "5.3", "5.4", "6.2", "6.3", "6.4", "6.5", "7.2", "7.3", "7.4", "7.5", "8.1", "8.2")

sample.id2
sample.id

# NOTE: FIGURE OUT HOW TO HANDLE REPLICATES

new_labels <- c("1_5_1", "1_5_2", "1_200_1", "1_200_2", "1_400_1", "2_50_1", "2_200_1", "2_200_2", "2_400_1", "2_400_2", "3_200_1", "3_200_2", "3_400_1", "3_400_2", "4_400_1", "4_400_2", "5_200_1", "5_200_2", "5_400_1", "5_400_2", "6_200_1", "6_200_2", "6_400_1", "6_400_2", "7_200_1", "7_200_2", "7_400_1", "7_400_2", "8_400_1", "8_400_2", "9_400_1", "9_400_2", "10_210_1", "10_210_2", "11_400_1", "11_400_2", "12_140_1", "12_140_2", "12_350_1", "12_350_2", "13_350_1", "13_350_2", "14_150_1", "14_150_2", "15_400_1", "15_400_2", "15_400_3", "16_400_1", "16_400_2")

all.metadata$NewSample <- new_labels

```

```{r extract sample IDs}

illumina.names <- colnames(illumina.nocon)
split.names <- str_split(illumina.names, ".StatNo.")

sample.id <- c(1:length(split.names))
station.num <- c(1:length(split.names))
sample.num <- c(1:length(split.names))

i <- 1
for (i in 1:length(split.names)) {
  curr.name <- split.names[[i]]
  station.num <- curr.name[2]
  curr.id <- curr.name[1] 
  curr.trim.id <- substring(curr.id, str_length(curr.id) - 1, str_length(curr.id))
  if (substring(curr.trim.id, 1, 1) != ".") {
      curr.trim.id <- substring(curr.id, str_length(curr.id) - 2, str_length(curr.id))
  }
  curr.sample.id <- paste0(station.num, curr.trim.id)
  sample.id[i] <- curr.sample.id
}

sample.id[sample.id == "NA.2"] <- "6.2"
sample.id <- as.numeric(sample.id)

illumina.by.sample <- data.frame(t(illumina.nocon))

rowSums(illumina.by.sample)
rownames(illumina.by.sample) <- sample.id

colnames(illumina.by.sample) <- taxonomy

all.metadata$SAMPLE2 <- as.character(all.metadata$SAMPLE)

trimmed.metadata <- all.metadata[all.metadata$SAMPLE2 %in% sample.id,]

illumina.by.sample <- illumina.by.sample[order(as.numeric(row.names(illumina.by.sample))), ]

# DELETE ONCE METADATA IS UP TO DATE

metadata.rep <- rownames(illumina.by.sample) %in% all.metadata$SAMPLE
```

```{r make colsums}

make_colsums <- function(colnames, df) {
  return.vec <- c(1:length(df))
  i <- 1
  for (name in colnames) {
    val <- sum(as.numeric(df[[name]]))
    return.vec[i] <- val
    i <- i + 1
  }
  return(return.vec)
}

illumina.new.sample.id <- trimmed.metadata$NewSample # extract new illumina IDs

```

```{r organize by order, order, family}
split.taxons <- str_split(taxonomy, ";") # splits the taxonomic assignment into kingdom level

find.level <- function(order, vector) { # extracts the kingdom organization from the longer vector by indicating the number within each split you want to look at
  return.vec <- c(1:length(vector))
  for (i in 1:length(vector)) {
    curr.elem <- vector[[i]]
    to.add <- curr.elem[order]
    return.vec[i] <- to.add
  }
  return(list(return.vec))
}

# extracts the order, orderes, etc.
all.class <- find.level(3, split.taxons)
all.order <- find.level(4, split.taxons)
all.family <- find.level(5, split.taxons)
all.genus <- find.level(6, split.taxons)
all.species <- find.level(7, split.taxons)

sample.id <- (trimmed.metadata$NewSample)

t.illumina.sample <- data.frame(t(illumina.by.sample))
illumina.class <- aggregate(t.illumina.sample, by = list(all.class[[1]]), FUN = sum)
rownames(illumina.class) <- illumina.class$Group.1
illumina.class <- illumina.class[,2:length(colnames(illumina.class))]
colnames(illumina.class) <- sample.id

illumina.order <- aggregate(t.illumina.sample, by = list(all.order[[1]]), FUN = sum)
rownames(illumina.order) <- illumina.order$Group.1
illumina.order <- illumina.order[,2:length(colnames(illumina.order))]
colnames(illumina.order) <- sample.id

illumina.family <- aggregate(t.illumina.sample, by = list(all.family[[1]]), FUN = sum)
rownames(illumina.family) <- illumina.family$Group.1
illumina.family <- illumina.family[,2:length(colnames(illumina.family))]
colnames(illumina.family) <- sample.id

illumina.genus <- aggregate(t.illumina.sample, by = list((all.genus[[1]])), FUN = sum)
rownames(illumina.genus) <- illumina.genus$Group.1
illumina.genus <- illumina.genus[,2:length(colnames(illumina.genus))]
colnames(illumina.genus) <- sample.id

illumina.species <- aggregate(t.illumina.sample, by = list((all.species[[1]])), FUN = sum)
rownames(illumina.species) <- illumina.species$Group.1
illumina.species <- illumina.species[,2:length(colnames(illumina.species))]
colnames(illumina.species) <- sample.id

illumina.order



```

```{r}


# Separate dataframe with metadata
taxon.organization <- data.frame("Order" = all.order, "order" = all.order, "Family" = all.family, "Genus" = all.genus, "Species" = all.species)


# Overall species accumulition curve for all data
plot(specaccum(illumina.family)) + title("SAC by Family")
plot(specaccum(illumina.order)) + title("SAC by Order")
plot(specaccum(illumina.order)) + title("SAC by order")
plot(specaccum(illumina.species)) + title("SAC by Species")
plot(specaccum(illumina.genus)) + title("SAC by Genus")

```

```{r}

# function converts values in datafrae into percentages
convert.to.perc <- function(df) {
  return(df/rowSums(df))
}

df <- illumina.order
aggregate.by.ocean <- function(df) {
  df.t <- t(df)
  return.df <- aggregate(df.t, by = list(trimmed.metadata$OceanType), FUN = sum)
  rownames(return.df) <- return.df$Group.1
  return.df <- return.df[,2:length(colnames(return.df))]
  return(return.df)
}


order.ocean <- aggregate.by.ocean(illumina.order)
order.ocean <- aggregate.by.ocean(illumina.order)
family.ocean <- aggregate.by.ocean(illumina.family)
genus.ocean <- aggregate.by.ocean(illumina.genus)
species.ocean <- aggregate.by.ocean(illumina.species)

```


```{r}


inds <- which(trimmed.metadata$OceanType == unique(trimmed.metadata$OceanType)[1])

length(trimmed.metadata$OceanType)
colnames(illumina.order)
curr.ocean <- illumina.order[,inds]

sac.ocean <- function(df) {
  for (ocean in unique(trimmed.metadata$OceanType)) {
    inds <- which(trimmed.metadata$OceanType == ocean)
    curr.ocean <- df[inds,]
    plot(specaccum(curr.ocean))
    title(ocean)
  }
}

sac.ocean(illumina.species)


```


```{r preparing stacked bar charts by gathering data}

illumina.order
illumina.order.locale <- illumina.order
colnames(illumina.order.locale) <- key.metadata.illumina$Location2

illumina.class$Class <- rownames(illumina.class)
illumina.class.gather <- gather(illumina.class, key = "site", value = "reads", -c(Class)) # gathers the data into a format for stacked bar chart plotting
illumina.order$Order <- rownames(illumina.order)
illumina.order.loc <- illumina.order %>% subset(., select = -c(Order)) %>% t(.) %>% data.frame()
illumina.order.loc$Location <- key.metadata.illumina[order(key.metadata.illumina$Sample, decreasing = TRUE),"Location2"]
illumina.order.loc
illumina.order.gather <- gather(illumina.order, key = "site", value = "reads", -c(Order)) # gathers the data into a format for stacked bar chart plotting


illumina.order.locale$Order <- rownames(illumina.order.locale)
#illumina.order.locale.gather <- gather(illumina.order.locale, key = "site", value = "reads", -c(Order)) # gathers the data into a format for stacked bar chart plotting
illumina.family$Family <- rownames(illumina.family)
illumina.family.gather <- gather(illumina.family, key = "site", value = "reads", -c(Family)) # gathers the data into a format for stacked bar chart plotting
illumina.genus$Genus <- rownames(illumina.genus)
illumina.genus.gather <- gather(illumina.genus, key = "site", value = "reads", -c(Genus)) # gathers the data into a format for stacked bar chart plotting
illumina.species$Species <- rownames(illumina.species)
illumina.species.gather <- gather(illumina.species, key = "site", value = "reads", -c(Species)) # gathers the data into a format for stacked bar chart plotting

illumina.class.gather$site <- as.factor((illumina.class.gather$site))
illumina.order.gather$site <- as.factor((illumina.order.gather$site))
illumina.family.gather$site <-as.factor((illumina.family.gather$site))

minion.order <- (order.taxa) %>% data.frame()
minion.order$Order <- rownames(minion.order)
minion.order.gather <- gather(minion.order, key = "site", value = "reads", -c(Order)) # gathers the data into a format for stacked bar chart plotting
```


```{r creating conditions to split stacked bar chart by site information}

depth_400 <- c(1:length(illumina.order.gather$site))
order_sites <- c(1:length(illumina.order.gather$site))
i <- 1

for (elem in illumina.order.gather$site) {
  if (str_split(elem, "_")[[1]][2] == "400") {
    depth_400[i] <- 1
  } else {
    depth_400[i] <- 0
  }
  order_sites[i] <- str_split(elem, "_")[[1]][1]
  i <- i + 1
}

depth_200 <- c(1:length(illumina.order.gather$site))
i <- 1

for (elem in illumina.order.gather$site) {
  if (str_split(elem, "_")[[1]][2] == "200") {
    depth_200[i] <- 1
  } else {
    depth_200[i] <- 0
  }
  i <- i + 1
}

illumina.order.gather$FourHundred <- depth_400
illumina.order.gather$TwoHundred <- depth_200
illumina.order.gather$OrderSites <- as.numeric(order_sites)

order.taxa
illumina.order

```

```{r renaming minion data}

rownames(order.taxa) <- new_labels[1:38]

order.taxa$site <- rownames(order.taxa)

order.taxa.gather.prep <- t(order.taxa) %>% data.frame() 
order.taxa.gather.prep$Order <- rownames(order.taxa.gather.prep)
order.taxa.gather <- order.taxa.gather.prep %>% gather(., key = "site", value = "reads", -c(Order))

depth_400 <- c(1:length(order.taxa.gather$site))
order_sites <- c(1:length(order.taxa.gather$site))
i <- 1

order.taxa.gather$site <- str_sub(order.taxa.gather$site, 2)

for (elem in order.taxa.gather$site) {
  if (str_split(elem, "_")[[1]][2] == "400") {
    depth_400[i] <- 1
  } else {
    depth_400[i] <- 0
  }
  order_sites[i] <- str_split(elem, "_")[[1]][1]
  i <- i + 1
}

depth_200 <- c(1:length(order.taxa.gather$site))
i <- 1

for (elem in order.taxa.gather$site) {
  if (str_split(elem, "_")[[1]][2] == "200") {
    depth_200[i] <- 1
  } else {
    depth_200[i] <- 0
  }
  i <- i + 1
}

order.taxa.gather$FourHundred <- depth_400
order.taxa.gather$TwoHundred <- depth_200
order.taxa.gather$OrderSites <- as.numeric(order_sites)

order.taxa.gather$OrderSites

order.taxa.gather$reads <- as.numeric(order.taxa.gather$reads)

order.taxa.gather$reads
```

```{r plotting stacked bar charts illumina and minion}

stacked.illumina.all <- ggplot(illumina.order.gather, aes(x = reorder(site, OrderSites), y = reads, fill = Order)) + geom_bar(position = "fill", stat = "identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Sites")

stacked.illumina.400 <- ggplot(illumina.order.gather[which(illumina.order.gather$FourHundred == 1),], aes(x = reorder(site, OrderSites), y = reads, fill = Order)) + geom_bar(position = "fill", stat = "identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Sites")

stacked.illumina.200 <- ggplot(illumina.order.gather[which(illumina.order.gather$TwoHundred == 1),], aes(x = reorder(site, OrderSites), y = reads, fill = Order)) + geom_bar(position = "fill", stat = "identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Sites")

stacked.minion.all <- ggplot(order.taxa.gather, aes(x = reorder(site, OrderSites), y = reads, fill = Order)) + geom_bar(position = "fill", stat = "identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Sites")
 + 
  geom_text(label=c(rev(levels(order.taxa.gather$Order)),rev(levels(order.taxa.gather$Order))),
            position=position_stack(vjust=0.5))
stacked.minion.400 <- ggplot(order.taxa.gather[which(order.taxa.gather$FourHundred == 1),], aes(x = reorder(site, OrderSites), y = reads, fill = Order)) + geom_bar(position = "fill", stat = "identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Sites")

stacked.minion.200 <- ggplot(order.taxa.gather[which(order.taxa.gather$TwoHundred == 1),], aes(x = reorder(site, OrderSites), y = reads, fill = Order)) + geom_bar(position = "fill", stat = "identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Sites")



```



```{r}
ggplot(illumina.order.gather, aes(x = site, y = reads, fill = Order)) + geom_bar(position = "fill", stat = "identity", color = "black") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + xlab("Sample Number") + ylab("Percentage of Reads") + scale_x_discrete(labels = c("28.1" = "Reef", "28.11" = "Reef", "28.2" = "Reef", "18.2" = "Divergence Front", "18.3" = "Divergence Front", "16.2" = "OMZ Compression", "16.3" = "OMZ Compression", "12.2" = "Open Ocean", "12.3" = "Open Ocean", "8.1" = "Cyclonic Eddy", "8.2" = "Cyclonic Eddy", "4.1" = "Eddy Convergence", "4.2" = "Eddy Convergence", "6.2" = "Anticyclonic Eddy", "6.3" = "Anticyclonic Eddy", "6.4" = "Anticyclonic Eddy", "6.5" = "Anticyclonic Eddy", "19.1" = "Open Ocean", "19.2" = "Open Ocean", "17.1" = "Divergence", "17.2" = "Divergence", "17.3" = "Divergence", "17.4" = "Divergence", "13.1" = "Open Ocean", "13.2" = "Open Ocean", "7.2" = "Cyclonic Edge", "7.3" = "Cyclonic Edge", "7.4" = "Cyclonic Edge", "7.5" = "Cyclonic Edge", "5.1" = "Seamount Down", "5.2" = "Seamount Down", "5.3" = "Seamount Down", "5.4" = "Seamount Down", "45.11" = "Seamount Up", "45.12" = "Seamount Up", "3.1" = "Cyclonic Eddy", "3.2" = "Cyclonic Eddy", "3.3" = "Cyclonic Eddy"))

ggplot(illumina.family.gather, aes(x = site, y = reads, fill = Family)) + geom_bar(position = "fill", stat = "identity") + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

illumina.order
```

```{r}
key.metadata.illumina

key.metadata.illumina.2 <- key.metadata.illumina[order(row.names(key.metadata.illumina)), ]

rownames(key.metadata.illumina.2) <- as.numeric(rownames(key.metadata.illumina.2))
key.metadata.illumina.2 <- key.metadata.illumina[order(row.names(key.metadata.illumina)), ]
key.metadata.illumina.2
         
```


```{r}

col <- colnames(illumina.order)[1]

for (col in colnames(illumina.order)) {
  temp.one <- data.frame(illumina.order[,col])
  temp.one$Order <- rownames(illumina.order)
  ggplot(temp.one, aes(x = Order, y = illumina.order...col.)) + geom_bar(stat = "identity") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
}


```

```{r}

# Trying to figure out how to match this data up with the metadata but not succeeding thus far

div.order <- diversity(data.frame(t(illumina.order.percentage)), index = "shannon")
div.order <- t(illumina.order.percentage) %>% data.frame() %>% select_if(~ !any(is.na(.)))  %>% diversity()
div.family <- t(illumina.family.percentage) %>% data.frame() %>% select_if(~ !any(is.na(.)))  %>% diversity()
div.genus <- t(illumina.genus.percentage) %>% data.frame() %>% select_if(~ !any(is.na(.)))  %>% diversity()
div.species <- t(illumina.species.percentage) %>% data.frame() %>% select_if(~ !any(is.na(.)))  %>% diversity()

trimmed.metadata$ShannonOrder <- div.order
trimmed.metadata$ShannonFamily <- div.family
trimmed.metadata$ShannonGenus <- div.genus
trimmed.metadata$ShannonSpecies <- div.species


ggplot(data = trimmed.metadata, aes(x = ShannonOrder, y = OceanType, fill = OceanType)) + geom_boxplot() + xlab("Shannon-Weiner Diversity Index") + ggtitle("Order Diversity")


ggplot(data = trimmed.metadata, aes(x = ShannonOrder, y = GeneralLocale, fill = GeneralLocale)) + geom_boxplot() + xlab("Shannon-Weiner Diversity Index") + ggtitle("Order Diversity, Fine Locations") + ylab("Ocean Feature")


general.locale <- list(trimmed.metadata$GeneralLocale)[[1]]
general.locale <- as.character(general.locale)
general.locale[general.locale == "Swordfish Seamount"] <- "Anticyclonic Eddy"
trimmed.metadata$General.Locale.Edit <- general.locale

ggplot(data = trimmed.metadata, aes(x = ShannonOrder, y = General.Locale.Edit, fill = General.Locale.Edit)) + geom_boxplot() + xlab("Shannon-Weiner Diversity Index") + ggtitle("Family Diversity, Swordfish is Anticyclonic")


```

```{r pairwise comps for shannon div}
library(rstatix)

key.metadata.illumina$Locale <- as.character(key.metadata.illumina$Locale)
key.metadata.illumina$Depth <- as.numeric(key.metadata.illumina$Depth)
key.metadata.illumina$Hour <- as.numeric(key.metadata.illumina$Hour)
key.metadata.illumina$Latitude <- as.numeric(key.metadata.illumina$Latitude)
key.metadata.illumina$TimeOfDay <- as.character(key.metadata.illumina$TimeOfDay)

key.metadata.minion$Locale <- as.character(key.metadata.minion$Locale)
key.metadata.minion$Depth <- as.numeric(key.metadata.minion$Depth)
key.metadata.minion$Hour <- as.numeric(key.metadata.minion$Hour)
key.metadata.minion$Latitude <- as.numeric(key.metadata.minion$Latitude)
key.metadata.minion$TimeOfDay <- as.character(key.metadata.minion$TimeOfDay)


locale.ill.t <- t_test(key.metadata.illumina, Diversity ~ Locale)
locale.ill.t
#locale2.ill.t <- t_test(key.metadata.illumina, Diversity ~ Location2)
#locale2.ill.t
depth.ill.t <- t_test(key.metadata.illumina, Diversity ~ Depth)
depth.ill.t
hour.ill.t <- t_test(key.metadata.illumina, Diversity ~ Hour)
hour.ill.t
timeofday.ill.t <- t_test(key.metadata.illumina, Diversity ~ TimeOfDay) 
timeofday.ill.t
lat.ill.t <- t_test(key.metadata.illumina, Diversity ~ Latitude)
lat.ill.t

locale.min.t <- t_test(key.metadata.minion, Diversity ~ Locale)
locale.min.t
depth.min.t <- t_test(key.metadata.minion, Diversity ~ Depth)
depth.min.t
hour.min.t <- t_test(key.metadata.minion, Diversity ~ Hour)
hour.min.t
timeofday.min.t <- t_test(key.metadata.minion, Diversity ~ TimeOfDay)
timeofday.min.t
lat.min.t <- t_test(key.metadata.minion, Diversity ~ Latitude)
lat.min.t

library(openxlsx)

dataset_names_ill <- list('Locale_Illumina' = locale.ill.t, 'Depth_Illumina' = depth.ill.t, 'Hour_Illumina' = hour.ill.t, 'TimeofDay_Illumina' = timeofday.ill.t, 'Latitude_Illumina' = lat.ill.t)
write.xlsx(dataset_names_ill, file = 'ShannonDiv_Pairwise_Illumina.xlsx')


dataset_names_min <- list('Locale_Minion' = locale.min.t, 'Depth_Minion' = depth.min.t, 'Hour_Minion' = hour.min.t, 'TimeofDay_Minion' = timeofday.min.t, 'Latitude_Minion' = lat.min.t)
write.xlsx(dataset_names_min, file = 'ShannonDiv_Pairwise_Minion.xlsx')


locale.ill.t <- t_test(key.metadata.illumina, Diversity ~ Locale) %>% .[which(.$p < 0.05 & .$p.adj.signif != "ns"),]
locale.ill.t
depth.ill.t <- t_test(key.metadata.illumina, Diversity ~ Depth) %>% .[which(.$p < 0.05 & .$p.adj.signif != "ns"),]
depth.ill.t
hour.ill.t <- t_test(key.metadata.illumina, Diversity ~ Hour) %>% .[which(.$p < 0.05 & .$p.adj.signif != "ns"),]
hour.ill.t
timeofday.ill.t <- t_test(key.metadata.illumina, Diversity ~ TimeOfDay) %>% .[which(.$p < 0.05 & .$p.adj.signif != "ns"),]
timeofday.ill.t
lat.ill.t <- t_test(key.metadata.illumina, Diversity ~ Latitude) %>% .[which(.$p < 0.05 & .$p.adj.signif != "ns"),]
lat.ill.t

locale.min.t <- t_test(key.metadata.minion, Diversity ~ Locale) %>% .[which(.$p < 0.05 & .$p.adj.signif != "ns"),]
locale.min.t
depth.min.t <- t_test(key.metadata.minion, Diversity ~ Depth) %>% .[which(.$p < 0.05 & .$p.adj.signif != "ns"),]
depth.min.t
hour.min.t <- t_test(key.metadata.minion, Diversity ~ Hour) %>% .[which(.$p < 0.05 & .$p.adj.signif != "ns"),]
hour.min.t
timeofday.min.t <- t_test(key.metadata.minion, Diversity ~ TimeOfDay) %>% .[which(.$p < 0.05 & .$p.adj.signif != "ns"),]
timeofday.min.t
lat.min.t <- t_test(key.metadata.minion, Diversity ~ Latitude) %>% .[which(.$p < 0.05 & .$p.adj.signif != "ns"),]
lat.min.t

df <- lat.min.t
i <- 1

timeofday.ill.t
make.couplets <- function(df) {
  list.1 <- as.list(df$group1)
  list.2 <- as.list(df$group2)
  return.vec <- list()
  for (i in 1:length(list.1)) {
    val.1 <- list.1[[i]]
    val.2 <- list.2[[i]]
    return.vec[[i]] <- (c(val.1, val.2))
  }
  
  return(return.vec)
}

make.couplets(hour.min.t) %>% unique()

```

```{r}

library(RColorBrewer)
library(ggpubr)

# NO significant differences to show
depth.div.illumina <- ggplot(data = key.metadata.illumina, aes(y = Diversity, x = -Depth, group = -Depth, color = -Depth)) + geom_boxplot(size = 0.5, width =20) + ylab("Shannon-Weiner Diversity Index") +  xlab("Depth") + xlim( -450, 20) + theme_classic()

depth.div.illumina <- ggplot(data = key.metadata.illumina, aes(y = Diversity, x = as.character(Depth), group = as.character(Depth), color = as.character(Depth))) + geom_boxplot() + ylab("Shannon-Weiner Diversity Index") + xlab("Depth")  + theme_classic() + theme(axis.title.x = element_blank(), legend.position = "none", axis.title.y = element_blank(), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) + ylim(0, 2.5)

depth.div.illumina



key.metadata.illumina <- key.metadata.illumina[order(key.metadata.illumina$Latitude),]
lat.div.illumina <- ggplot(key.metadata.illumina, aes(y = Diversity, x = factor(as.character(Latitude), levels = c("6", "8", "9", "10", "13", "14", "17", "18", "19")), color = as.character(Latitude), group = as.character(Latitude))) + xlab("Latitude") + ylab("Shannon-Weiner Diversity Index")  + geom_boxplot()+ scale_fill_distiller(palette = "BuPu") + theme_classic()+ theme(legend.position = "none") + theme(axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) + ylim(0, 2.5)
lat.div.illumina

key.metadata.illumina$Hour

key.metadata.illumina <- key.metadata.illumina[order(key.metadata.illumina$TimeOfDay),]
#tod.div.illumina <- ggboxplot(key.metadata.illumina, y = "Diversity", x = "TimeOfDay", color = "TimeOfDay", legend = "none") +  xlab("Time of Day of Sample Collection") + ylab("Shannon-Weiner Diversity Index") + scale_fill_distiller(palette = "BuPu") + stat_compare_means(comparisons = make.couplets(timeofday.ill.t), label = "p.signif", hide.ns = TRUE, method = "t.test") + theme(axis.title.x = element_blank(), axis.title.y = element_blank()) + ylim(0, 2.5)
tod.div.illumina <- ggplot(data = key.metadata.illumina, aes(y = Diversity, x = factor(TimeOfDay, levels = c("Morning", "Afternoon", "Night")), group = TimeOfDay, color = TimeOfDay)) + geom_boxplot() + ylab("Shannon-Weiner Diversity Index") + xlab("Time of Day")  + theme_classic() + theme(axis.title.x = element_blank(), legend.position = "none", axis.title.y = element_blank(), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12)) + ylim(0, 2.5)
tod.div.illumina

make.couplets(depth.min.t)
depth.min.t
depth.div.minion <- ggboxplot(key.metadata.minion, y = "Diversity", x = "Depth", color = "Depth", legend = "none") +xlab("Depth of Sample Collection (m)") + ylab("Shannon-Weiner Diversity Index") + scale_fill_distiller(palette = "BuPu") + stat_compare_means(comparisons = make.couplets(depth.min.t), label = "p.signif", hide.ns = TRUE, method = "t.test") + theme( axis.title.y = element_blank()) + ylim(0, 2.5)
depth.div.minion

lat.div.minion <- ggboxplot(key.metadata.minion, y = "Diversity", x = "Latitude", color = "Latitude", legend = "none") +  xlab("Latitude") + ylab("Shannon-Weiner Diversity Index") + scale_fill_distiller(palette = "BuPu") + stat_compare_means(comparisons = make.couplets(lat.min.t), label = "p.signif", hide.ns = TRUE, method = "t.test") + theme(axis.title.y = element_blank()) + ylim(0, 2.5)
lat.div.minion

make.couplets(hour.min.t)
time.div.minion <- ggboxplot(key.metadata.minion, y = "Diversity", x = "Hour", color = "Hour", legend = "none") + xlab("Hour of Sample Collection") + ylab("Shannon-Weiner Diversity Index") + stat_compare_means(comparisons = list(c("10", "16"), c("11", "16"), c("16", "22"), c("16", "23")), label = "p.signif", hide.ns = TRUE, method = "t.test") + ylim(0, 2.5)
time.div.minion

key.metadata.minion

key.metadata.minion$TimeOfDay <- factor(key.metadata.minion$TimeOfDay, levels = c("Morning", "Afternoon", "Night"))
tod.div.minion <- ggboxplot(key.metadata.minion, y = "Diversity", x = "TimeOfDay", color = "TimeOfDay", legend = "none") +  xlab("Time of Day of Sample Collection") + ylab("Shannon-Weiner Diversity Index") + scale_fill_distiller(palette = "BuPu") + stat_compare_means(comparisons = make.couplets(timeofday.min.t), label = "p.signif", hide.ns = TRUE, method = "t.test") + theme(axis.title.y = element_blank()) + ylim(0, 2.5)
tod.div.minion

general.locale <- list(trimmed.metadata$GeneralLocale)[[1]]
general.locale <- as.character(general.locale)
general.locale[general.locale == "Swordfish Seamount"] <- "Anticyclonic Eddy"
trimmed.metadata$General.Locale.Edit <- general.locale

grid.arrange(depth.div.illumina, lat.div.illumina, tod.div.illumina, depth.div.minion, lat.div.minion, tod.div.minion, ncol = 3, nrow = 2)
env.var.box
```


```{r}

library(ggfortify)

for.order.nmds <- t(illumina.order.percentage) %>% data.frame() %>% select_if(~ !any(is.na(.))) %>% .[rowSums(.[])>0,]

trimmed.ocean.type <- trimmed.metadata$OceanType
trimmed.try.2 <- trimmed.metadata$`Updated Location`
trimmed.gen <- trimmed.metadata$GeneralLocale
trimmed.edit <- trimmed.metadata$General.Locale.Edit
trimmed.depth <- trimmed.metadata$General.Locale.Edit

order.nmds <- metaMDS(for.order.nmds, k = 10, trymax = 100, trace = F, autotransform = FALSE, distance="bray")
order.nmds$iters

NMDS3.minion <- metaMDS((order.taxa.perc), k = 10, trymax = 100, trace = F, autotransform = FALSE, distance = "bray")
NMDS3.minion$iters

nmds.en.ill <- key.metadata.illumina %>% select(-c(Diversity, Locale, Location2, OceanType, HourGroup, Hour, Density, Sample))
nmds.en.ill$Depth <- as.character(nmds.en.ill$Depth)
nmds.en.ill$Latitude <- as.character(nmds.en.ill$Latitude)

en.ill = envfit(order.nmds, nmds.en.ill, permutations = 999, na.rm = TRUE)

nmds.en.min <- key.metadata.minion %>% select(-c(Diversity, Locale, OceanType, LocaleEdit, HourGroup, Time, Hour, Density))
nmds.en.min$Depth <- as.character(nmds.en.min$Depth)
nmds.en.min$Latitude <- as.character(nmds.en.min$Latitude)
en.min = envfit(NMDS3.minion, nmds.en.min, permutations = 999, na.rm = TRUE)
en.min
en.ill

```

```{r nmds multiple environmental illumina}
library(ggrepel)
plot(NMDS3.minion, type = "t")
plot(order.nmds, type = "t")


data.scores = as.data.frame(scores(order.nmds))
data.scores$Station = key.metadata.illumina$Location2
#extract NMDS scores (x and y coordinates) for sites from newer versions of vegan package

#add 'season' column as before

en_coord_cont = as.data.frame(scores(en.ill, "vectors")) * ordiArrowMul(en.ill)
en_coord_cat = as.data.frame(scores(en.ill, "factors")) * ordiArrowMul(en.ill)

gg = ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
     geom_point(data = data.scores, aes(colour = Station), size = 3, alpha = 0.5) + 
     theme(axis.title = element_text(size = 10, face = "bold", colour = "grey30"), 
     panel.background = element_blank(), panel.border = element_rect(fill = NA, colour = "grey30"), 
     axis.ticks = element_blank(), axis.text = element_blank(), legend.key = element_blank(), 
     legend.title = element_text(size = 10, face = "bold", colour = "grey30"), 
     legend.text = element_text(size = 9, colour = "grey30")) +
     labs(colour = "Station")
     
gg

gg.ill.nmds.multiple = ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
     geom_point(data = data.scores, aes(colour = Station), size = 3, alpha = 0.5) + 
     geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
       data = en_coord_cont, size =1, alpha = 0.5, colour = "grey30") +
     geom_point(data = en_coord_cat, aes(x = NMDS1, y = NMDS2), 
       shape = "diamond", size = 4, alpha = 0.6, colour = "navy") +
     geom_text_repel(data = en_coord_cat, aes(x = NMDS1, y = NMDS2+0.04), 
       label = c("140 m", "150 m", "200 m", "210 m", "350 m", "400 m", "10ºN", "13ºN", "14ºN", "17ºN", "18ºN", "19ºN", "6ºN", "8ºN", "9ºN", "Morning", "Afternoon", "Night"), colour = "navy", fontface = "bold") + 
     geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30", 
       fontface = "bold", label = row.names(en_coord_cont)) + 
     theme(axis.title = element_text(size = 10, face = "bold", colour = "grey30"), 
       panel.background = element_blank(), panel.border = element_rect(fill = NA, colour = "grey30"), 
       axis.ticks = element_blank(), axis.text = element_blank(), legend.key = element_blank(), 
       legend.title = element_text(size = 10, face = "bold", colour = "grey30"), 
       legend.text = element_text(size = 9, colour = "grey30"))+
     labs(colour = "Station") + ggtitle("NMDS for Multiple Environmental Variables (Illumina)")

gg.ill.nmds.multiple



```

```{r nmds multiple environmental minion}

data.scores = as.data.frame(scores(NMDS3.minion))
data.scores$Station = key.metadata.minion$Locale
#extract NMDS scores (x and y coordinates) for sites from newer versions of vegan package

#add 'season' column as before

en_coord_cont = as.data.frame(scores(en.min, "vectors")) * ordiArrowMul(en.min)
en_coord_cat = as.data.frame(scores(en.min, "factors")) * ordiArrowMul(en.min)

gg = ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
     geom_point(data = data.scores, aes(colour = Station), size = 3, alpha = 0.5) + 
     theme(axis.title = element_text(size = 10, face = "bold", colour = "grey30"), 
     panel.background = element_blank(), panel.border = element_rect(fill = NA, colour = "grey30"), 
     axis.ticks = element_blank(), axis.text = element_blank(), legend.key = element_blank(), 
     legend.title = element_text(size = 10, face = "bold", colour = "grey30"), 
     legend.text = element_text(size = 9, colour = "grey30")) +
     labs(colour = "Station")
     
gg
gg.minion.nmds.multiple = ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) + 
     geom_point(data = data.scores, aes(colour = Station), size = 3, alpha = 0.5) + 
     geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
       data = en_coord_cont, size =1, alpha = 0.5, colour = "grey30") +
     geom_point(data = en_coord_cat, aes(x = NMDS1, y = NMDS2), 
       shape = "diamond", size = 4, alpha = 0.6, colour = "navy") +
     geom_text_repel(data = en_coord_cat, aes(x = NMDS1, y = NMDS2+0.04), 
       label = c("200 m", "210 m", "350 m", "400 m", "5 m", "50 m", "10ºN", "13ºN", "14ºN", "17ºN", "18ºN", "19ºN", "Afternoon", "Morning", "Night"), colour = "navy", fontface = "bold") + 
     geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30", 
       fontface = "bold", label = row.names(en_coord_cont)) + 
     theme(axis.title = element_text(size = 10, face = "bold", colour = "grey30"), 
       panel.background = element_blank(), panel.border = element_rect(fill = NA, colour = "grey30"), 
       axis.ticks = element_blank(), axis.text = element_blank(), legend.key = element_blank(), 
       legend.title = element_text(size = 10, face = "bold", colour = "grey30"), 
       legend.text = element_text(size = 9, colour = "grey30"))+
     labs(colour = "Station") + ggtitle("NMDS for Multiple Environmental Variables (Minion)")

gg.minion.nmds.multiple


```

```{r function to ggplot NMDS}



ggplot.NMDS <- function(df, meta.plot,val.name) {
  data.scores <- as.data.frame(scores(df))  #Using the scores function from vegan to extract the site scores and convert to a data.frame
  
  data.scores$site <- rownames(data.scores)  # create a column of site names, from the rownames of data.scores
  data.scores$val <- meta.plot
  
  species.scores <- as.data.frame(scores(order.nmds, "species"))  #Using the scores function from vegan to extract the species scores and convert to a data.frame
  species.scores$species <- rownames(species.scores)  # create a column of species, from the rownames of species.scores

  
  plot <- ggplot() + 
    geom_point(data=data.scores,aes(x=NMDS1,y=NMDS2,colour=val),size=4) +
    coord_equal() +
    theme_bw() + 
    theme(axis.text.x = element_blank(),  # remove x-axis text
          axis.text.y = element_blank(), # remove y-axis text
          axis.ticks = element_blank(),  # remove axis ticks
          axis.title.x = element_text(size=18), # remove x-axis labels
          axis.title.y = element_text(size=18), # remove y-axis labels
          panel.background = element_blank(), 
          panel.grid.major = element_blank(),  #remove major-grid labels
          panel.grid.minor = element_blank(),  #remove minor-grid labels
          plot.background = element_blank())+ labs(color=val.name) 
  return(plot)
}


ggplot.NMDS.depth <- function(df, meta.plot,val.name) {
  data.scores <- as.data.frame(scores(df))  #Using the scores function from vegan to extract the site scores and convert to a data.frame
  
  data.scores$site <- rownames(data.scores)  # create a column of site names, from the rownames of data.scores
  data.scores$val <- meta.plot
  
  species.scores <- as.data.frame(scores(order.nmds, "species"))  #Using the scores function from vegan to extract the species scores and convert to a data.frame
  species.scores$species <- rownames(species.scores)  # create a column of species, from the rownames of species.scores

  
  plot <- ggplot() + 
    geom_point(data=data.scores,aes(x=NMDS1,y=NMDS2,colour=-val),size=4) +
    coord_equal() +
    theme_bw() + 
    theme(axis.text.x = element_blank(),  # remove x-axis text
          axis.text.y = element_blank(), # remove y-axis text
          axis.ticks = element_blank(),  # remove axis ticks
          axis.title.x = element_text(size=18), # remove x-axis labels
          axis.title.y = element_text(size=18), # remove y-axis labels
          panel.background = element_blank(), 
          panel.grid.major = element_blank(),  #remove major-grid labels
          panel.grid.minor = element_blank(),  #remove minor-grid labels
          plot.background = element_blank())+ labs(color=val.name) 
  return(plot)
}
tabasco(for.order.nmds)

```


```{r}

minion.metadata <- read.csv("metadata.csv") %>% .[1:38,]

NMDS3.minion
for.order.nmds 

colnames(order.taxa.perc)
colnames(for.order.nmds)

minion.metadata[["OceanType"]]
ggplot.NMDS(NMDS3.minion, key.metadata.minion$Locale, "Locale") + ggtitle("Minion, Fine")

```


```{r nmds for illumina}


p.i.order.locale <- ggplot.NMDS(order.nmds, trimmed.try.2, "Locale") + ggtitle("NMDS by Order, Location, Illumina")
p.i.order.depth <- ggplot.NMDS.depth(order.nmds, key.metadata.illumina$Depth, "Depth") + ggtitle("NMDS by Order, Depth, Illumina")
p.i.order.latitude <- ggplot.NMDS(order.nmds, key.metadata.illumina$Latitude, "Latitude") + ggtitle("NMDS by Order, Latitude, Illumina")
p.i.order.hour <- ggplot.NMDS(order.nmds, key.metadata.illumina$Hour, "Hour of Cast") + ggtitle("NMDS by Order, Hour, Illumina")
p.i.order.group <- ggplot.NMDS(order.nmds, key.metadata.illumina$TimeOfDay, "Time Of Day") + ggtitle("NMDS by Order, Time of Day, Illumina")

p.i.order.locale
p.i.order.depth
p.i.order.latitude
p.i.order.hour
p.i.order.group
# DENDOGRAM (done)
# ANOVA (done)
# BOX PLOTS BY DIFF VARIABLES (done)
# NMDS BY DIFF VARIABLES (done)

```

```{r nmds for minion}

p.i.order.locale <- ggplot.NMDS(NMDS3.minion, key.metadata.minion$Locale, "Location") + ggtitle("NMDS by Order, Location, Minion")
p.i.order.depth <- ggplot.NMDS.depth(NMDS3.minion, key.metadata.minion$Depth, "Depth") + ggtitle("NMDS by Order, Depth, Minion")
p.i.order.latitude <- ggplot.NMDS(NMDS3.minion, key.metadata.minion$Latitude, "Latitude") + ggtitle("NMDS by Order, Latitude, Minion")
p.i.order.hour <- ggplot.NMDS(NMDS3.minion, key.metadata.minion$Hour, "Hour of Cast") + ggtitle("NMDS by Order, Hour, Minion")
p.i.order.group <- ggplot.NMDS(NMDS3.minion, key.metadata.minion$TimeOfDay, "Time Of Day") + ggtitle("NMDS by Order, Time of Day, Minion")

p.i.order.locale
p.i.order.depth
p.i.order.latitude
p.i.order.hour
p.i.order.group
# DENDOGRAM (done)
# ANOVA (done)
# BOX PLOTS BY DIFF VARIABLES (done)
# NMDS BY DIFF VARIABLES (done)

```

```{r}


ggplot.NMDS(family.nmds, trimmed.ocean.type) + ggtitle("Family, Ocean")
ggplot.NMDS(family.nmds, trimmed.gen) + ggtitle("Family, Fine")
ggplot.NMDS(family.nmds, trimmed.edit) + ggtitle("Family, Swordfish")


length(trimmed.depth)
ggplot.NMDS(family.nmds, trimmed.depth) + ggtitle("Family, Ocean")
ggplot.NMDS(family.nmds, trimmed.gen) + ggtitle("Family, Fine")
ggplot.NMDS(family.nmds, trimmed.edit) + ggtitle("Family, Swordfish")

```

```{r}


ggplot.NMDS(genus.nmds, trimmed.ocean.type)
ggplot.NMDS(genus.nmds, trimmed.gen)
ggplot.NMDS(genus.nmds, trimmed.edit)

```

```{r tukey multiple comparison of means i.e. pairwise comparisons}

dist.order.ill <- vegdist(illumina.order.t)
fac.depth <- as.factor(key.metadata.illumina$Depth)
fac.locale <- as.factor(key.metadata.illumina$Locale)
fac.oceantype <- as.factor(key.metadata.illumina$OceanType)
fac.latitude <- as.factor(key.metadata.illumina$Latitude)
fac.hour <- as.factor(key.metadata.illumina$Hour)
big.group <- as.factor(round(key.metadata.illumina$Hour/6, 0))
key.metadata.illumina

bd.depth.i <- betadisper(dist.order.ill, fac.depth)
bd.locale.i <- betadisper(dist.order.ill, fac.locale)
bd.oceantype.i <- betadisper(dist.order.ill, fac.oceantype)
bd.latitude.i <- betadisper(dist.order.ill, fac.latitude)
bd.hour.i <- betadisper(dist.order.ill, fac.hour)
bd.hour2.i <- betadisper(dist.order.ill, big.group)


bd.depth.i %>% TukeyHSD()
bd.locale.i %>% TukeyHSD()
bd.oceantype.i %>% TukeyHSD()
bd.latitude.i %>% TukeyHSD()
bd.hour.i %>% TukeyHSD()
bd.hour2.i %>% TukeyHSD()


fac.depth <- as.factor(key.metadata.minion$Depth)
fac.locale <- as.factor(key.metadata.minion$Locale)
fac.oceantype <- as.factor(key.metadata.minion$OceanType)
fac.latitude <- as.factor(key.metadata.minion$Latitude)
fac.hour <- as.factor(key.metadata.minion$Hour)
big.group <- as.factor(round(key.metadata.minion$Hour/6, 0))
key.metadata.minion

bd.depth.i <- betadisper(dist.order.minion, fac.depth)
bd.locale.i <- betadisper(dist.order.minion, fac.locale)
bd.oceantype.i <- betadisper(dist.order.minion, fac.oceantype)
bd.latitude.i <- betadisper(dist.order.minion, fac.latitude)
bd.hour.i <- betadisper(dist.order.minion, fac.hour)
bd.hour2.i <- betadisper(dist.order.minion, big.group)

bd.depth.i %>% TukeyHSD()
bd.locale.i %>% TukeyHSD()
bd.oceantype.i %>% TukeyHSD()
bd.latitude.i %>% TukeyHSD()
bd.hour.i %>% TukeyHSD()
bd.hour2.i %>% TukeyHSD()

```

```{r pcoa and cca for illumina}
library(ape)

pcoa.results <- illumina.order.t[which(key.metadata.illumina$Locale != "Swordfish Seamount" & key.metadata.illumina$Locale != "Subtropical Gyre" & key.metadata.illumina$Locale != "Eddy convergence"),] %>% vegdist(., method = "bray") %>% pcoa(.)

pcoa.gg <- key.metadata.illumina[which(key.metadata.illumina$Locale != "Swordfish Seamount" & key.metadata.illumina$Locale != "Subtropical Gyre" & key.metadata.illumina$Locale != "Eddy convergence"),] %>% data.frame("PCoA1" = pcoa.results$vectors[,1], "PCoA2" = pcoa.results$vectors[,2], "Locale" = .$Locale, "Hour" = .$Hour)

ggplot(data = pcoa.gg, aes(x = PCoA1, y = PCoA2, colour = Locale)) + geom_point()



pcoa.results <- pcoa(dist.order.illumina)

pcoa.gg <- data.frame("PCoA1" = pcoa.results$vectors[,1], "PCoA2" = pcoa.results$vectors[,2], "Hour" = key.metadata.illumina$Hour)

ggplot(data = pcoa.gg, aes(x = PCoA1, y = PCoA2, colour = Hour)) + geom_point()

# Ugly AF plots
cca(illumina.order.t ~ Locale, key.metadata.illumina) %>% plot()
cca(illumina.order.t ~ Hour, key.metadata.illumina) %>% plot()
cca(illumina.order.t ~ TimeOfDay, key.metadata.illumina) %>% plot()

```


```{r simper analyses}

illumina.order.t <- t(illumina.order)
simper.illumina <- simper(illumina.order.t, group = as.factor(key.metadata.illumina$Locale)) 
simper.illumina.depth <- simper(illumina.order.t, group = as.factor(key.metadata.illumina$Depth)) 
simper.illumina.depth
simper.illumina$`Cyclonic Eddy_Anticyclonic Eddy`

simper.illumina


simper.df <- simper.illumina$`OMZ Compression_Anticyclonic Eddy`
simper.illumina$`OMZ Compression_Cyclonic Eddy`
simper.illumina$`OMZ Compression_Cyclonic Edge`
simper.illumina$`OMZ Compression_Divergence`
simper.illumina$`OMZ Compression_Divergence Front`
simper.illumina$`Kingman Reef_OMZ Compression`
simper.illumina$`OMZ Compression_Swordfish Seamount`

simper.minion <- simper(order.taxa, group = as.factor(key.metadata.minion$Locale))
```


```{r}
simper.illumina$`Anticyclonic Eddy_OMZ Compression`$cusum[2] - simper.illumina$`Anticyclonic Eddy_OMZ Compression`$cusum[2 -1]
cusum <- (simper.illumina$`Anticyclonic Eddy_OMZ Compression`$cusum)

convert.cusum <- function(cusum) {
  return.vec <- c(1:length(cusum))
  return.vec[1] <- cusum[1]
  for (i in 2:length(cusum)) {
    val = cusum[i] - cusum[i - 1]
    print(i)
    return.vec[i] <- val
  }
  return(return.vec)
}

simper.df <- simper.illumina$`OMZ Compression_Divergence Front`
plot.simper <- function(simper.df) {
  ordered.sp <- simper.df$ord
  species <- simper.df$species[order(ordered.sp)]
  sd <- simper.df$sd[order(ordered.sp)]
  cusum <- simper.df$cusum
  avg <- simper.df$average[order(ordered.sp)]
  df <- data.frame("Species" = species, "SD" = sd, "Contribution" = cusum, "Average" = avg)
  plot.df <- df[which(df$Contribution < 0.99),]
  plot.df$ContributionVal <- convert.cusum(plot.df$Contribution)
  return.plot <- ggplot(plot.df, aes(x = reorder(Species, -ContributionVal), y = ContributionVal)) + geom_bar(stat = "identity", aes(fill = Species)) + theme_bw() + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + xlab("Order") + ylab("Contribution to Dissimilarity")
  
  return(return.plot)
}


simp.omz.anticyc.eddy <- plot.simper(simper.illumina$`Anticyclonic Eddy_OMZ Compression`)
simp.omz.anticyc.eddy <- simp.omz.anticyc.eddy + ggtitle("OMZ Compression vs. Anticyclonic Eddy") + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank())
simp.omz.cyc.eddy <- plot.simper(simper.illumina$`Cyclonic Eddy_OMZ Compression`)
simp.omz.cyc.eddy <- simp.omz.cyc.eddy + ggtitle("OMZ Compression vs. Cyclonic Eddy") + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank())
simp.omz.cyc.edge <- plot.simper(simper.illumina$`Cyclonic Edge_OMZ Compression`)
simp.omz.cyc.edge <- simp.omz.cyc.edge + ggtitle("OMZ Compression vs. Cyclonic Edge") + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank())
simp.omz.div <- plot.simper(simper.illumina$`OMZ Compression_Divergence`)
simp.omz.div <- simp.omz.div + ggtitle("OMZ Compression vs. Divergence") + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank())
simp.omz.div.front <- plot.simper(simper.illumina$`OMZ Compression_Divergence Front`)
simp.omz.div.front <- simp.omz.div.front + ggtitle("OMZ Compression vs. Divergence Front") + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank())
simp.omz.reef <- plot.simper(simper.illumina$`OMZ Compression_Kingman Reef`)
simp.omz.reef <- simp.omz.reef + ggtitle("OMZ Compression vs. Kingman Reef") + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank())
simp.omz.swordfish <- plot.simper(simper.illumina$`Swordfish Seamount_OMZ Compression`)
simp.omz.swordfish <- simp.omz.swordfish + ggtitle("OMZ Compression vs. Swordfish Seamount") + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank())

simper.illumina.grid <- grid.arrange(simp.omz.anticyc.eddy,simp.omz.cyc.eddy,simp.omz.cyc.edge,simp.omz.div,simp.omz.div.front,simp.omz.reef,simp.omz.swordfish,nrow = 3)
simper.illumina.grid
simp.anticyc.ocean.min <- plot.simper(simper.minion$`Anticyclonic Eddy_Open Ocean`)
simp.anticyc.ocean.min <- simp.anticyc.ocean.min + ggtitle("Anticyclonic Eddy vs. Open Ocean") + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank())
simp.ocean.keiahoe <- plot.simper(simper.minion$`Keiahoe/Hawai'i_Open Ocean`)
simp.ocean.keiahoe <- simp.ocean.keiahoe + ggtitle("Keiahoe/Hawai'i vs. Open Ocean")+ theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank())
simp.ocean.nearshore <- plot.simper(simper.minion$`Hawai'I Nearshore_Open Ocean`)
simp.ocean.nearshore <- simp.ocean.nearshore + ggtitle("Hawai'i Nearshore vs. Open Ocean") + theme(legend.position = "none", axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1), axis.title.x = element_blank(), axis.title.y = element_blank())

simper.minion.grid <- grid.arrange(simp.anticyc.ocean.min,simp.ocean.keiahoe,simp.ocean.nearshore, nrow = 3)
simper.illumina$`OMZ Compression_Cyclonic Edge`


simper.illumina$`Anticyclonic Eddy_OMZ Compression`
```


```{r}

test <- simper.illumina["Cyclonic Eddy_Eddy convergence"][[1]] %>% .[which(.$ratio > 0.5 & .$cumsum < 0.99),]
test
test$Order <- rownames(test)
curr.df
name <- names(simper.illumina)[1]

for (name in names(simper.illumina)) {
  curr.df <- simper.illumina[name][[1]] %>% .[which(.$ratio > 0.5 & .$cumsum < 0.99 & .$avb > 0 & .$ava > 0),]
  curr.df$Order <- rownames(curr.df)
  test <- rbind(test, curr.df)
}

test

most.val.member <- aggregate(test, by = list(test$Order), FUN = mean)
most.val.member

simper.illumina <- simper(illumina.order.t, group = as.factor(key.metadata.illumina$Location2))
(simper.illumina)

simper.minion <- simper(order.taxa, group = as.factor(key.metadata.minion$Locale))
(simper.minion)

```

```{r pcoa and cca for minion}

pcoa.results.min <- order.taxa[which(key.metadata.minion$Latitude == "19" | key.metadata.minion$Latitude == "10" | key.metadata.minion$Latitude == "13" | key.metadata.minion$Latitude == "18" | key.metadata.minion$Latitude == "14" | key.metadata.minion$Latitude == "17"),] %>% vegdist(.) %>% pcoa(.)

pcoa.results.min <- order.taxa %>% vegdist(.) %>% pcoa(.)

pcoa.gg.min <- data.frame("PCoA1" = pcoa.results.min$vectors[,1], "PCoA2" = pcoa.results.min$vectors[,2], "Locale" = key.metadata.minion$Locale, "Hour" = key.metadata.minion$Hour, "Latitude" = key.metadata.minion$Latitude, "Locale" = key.metadata.minion$OceanType)

ggplot(data = pcoa.gg.min, aes(x = PCoA1, y = PCoA2, colour = Latitude)) + geom_point()
ggplot(data = pcoa.gg.min, aes(x = PCoA1, y = PCoA2, colour = Hour)) + geom_point()
ggplot(data = pcoa.gg.min, aes(x = PCoA1, y = PCoA2, colour = Locale)) + geom_point()


pcoa.gg.min <- key.metadata.minion[which(key.metadata.minion$OceanType == "Near shore" | key.metadata.minion$OceanType == "Open Ocean" | key.metadata.minion$OceanType == "Anticyclonic eddy"),] %>% data.frame("PCoA1" = pcoa.results.min$vectors[,1], "PCoA2" = pcoa.results.min$vectors[,2], "Hour" = .$Hour, "Locale" = .$OceanType)

pcoa.gg.min

ggplot(data = pcoa.gg.min, aes(x = PCoA1, y = PCoA2, colour = Locale.1)) + geom_point()


# Ugly AF plots
cca(order.taxa ~ Locale, key.metadata.minion) %>% plot()
cca(order.taxa ~ Hour, key.metadata.minion) %>% plot()
cca(order.taxa ~ TimeOfDay, key.metadata.minion) %>% plot()

```

```{r}

colnames(key.metadata.illumina)


permanova.illumina <- adonis2(dist.order.illumina ~  Depth+ Latitude+ Temperature+ Chlorophyll+ Salinity+ Oxygen+ Density+ Hour, key.metadata.illumina, by = "margin")
permanova.illumina

permanova.minion <- adonis2(dist.order.minion ~ Depth+ Latitude+ Temperature+ Chlorophyll+ Salinity+ Oxygen+ Density+ Hour, key.metadata.minion, by = "margin")
permanova.minion

```
```

